# Generated by Django 2.0.6 on 2018-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('article', models.TextField()),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='date added')),
            ],
        ),
    ]
